// Package docs renders the CLI documentation from the live cobra command tree.
// It is the single source for both the `go generate` writer (tools/docgen) and
// the drift test, so the generator and the staleness check can never disagree.
// Everything user-facing flows from internal/branding.
package docs

import (
	"fmt"
	"sort"
	"strings"

	"github.com/husqylabs/stack/internal/branding"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const generatedNote = "<!-- Generated by `go generate ./...` (tools/docgen). Do not edit by hand. -->"

// Index renders the docs home page (docs/index.md), the landing page of the site.
func Index(root *cobra.Command) string {
	b := branding.B
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s\n\n%s\n\n", b.Title, generatedNote)
	fmt.Fprintf(&sb, "%s\n\n", root.Short)
	fmt.Fprintf(&sb, "`%s` manages **stacked pull requests** entirely client-side — no "+
		"backend server. The branch DAG is synced across teammates by embedding it as a "+
		"hidden comment in each PR description.\n\n", b.Name)

	sb.WriteString("## Get started\n\n")
	sb.WriteString("- **[Cheat sheet](cheatsheet.md)** — one-page quick reference and workflow recipes.\n")
	sb.WriteString("- **[Command reference](commands.md)** — every command, flag, and default.\n\n")

	sb.WriteString("## Install\n\n```sh\ngo build -o " + b.Name + " .\n```\n\n")

	fmt.Fprintf(&sb, "## Quickstart\n\n```sh\n"+
		"%[1]s %[2]s feature-a      # branch off the trunk and track it\n"+
		"# ...commit work...\n"+
		"%[1]s %[2]s feature-b      # stack feature-b on feature-a\n"+
		"# ...commit work...\n\n"+
		"export %[4]s=$(gh auth token)\n"+
		"%[1]s %[3]s --owner ORG --repo REPO   # push the stack and open PRs\n"+
		"```\n", b.Name, b.CmdStart, b.CmdSubmit, b.Env("TOKEN"))
	return sb.String()
}

// MkdocsConfig renders mkdocs.yml. Site name/description come from branding so a
// rebrand regenerates the site config too.
func MkdocsConfig() string {
	b := branding.B
	return fmt.Sprintf(`# %s
site_name: %s
site_description: %s
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
nav:
  - Home: index.md
  - Cheat sheet: cheatsheet.md
  - Command reference: commands.md
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
`, strings.TrimPrefix(strings.TrimSuffix(generatedNote, " -->"), "<!-- "), b.Title, b.Tagline)
}

// Reference renders the full command reference (docs/commands.md).
func Reference(root *cobra.Command) string {
	cmds := visibleCommands(root)
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — command reference\n\n%s\n\n", branding.B.Name, generatedNote)
	fmt.Fprintf(&b, "%s\n\n", root.Short)

	for _, c := range cmds {
		fmt.Fprintf(&b, "- [`%s %s`](#%s)\n", branding.B.Name, c.Name(), c.Name())
	}
	b.WriteString("\n")

	for _, c := range cmds {
		fmt.Fprintf(&b, "## %s\n\n", c.Name())
		fmt.Fprintf(&b, "%s\n\n", c.Short)
		fmt.Fprintf(&b, "```\n%s %s\n```\n\n", branding.B.Name, useArgsWithFlags(c))
		if long := strings.TrimSpace(c.Long); long != "" {
			fmt.Fprintf(&b, "%s\n\n", long)
		}
		if ft := flagsTable(c); ft != "" {
			b.WriteString(ft)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// Cheatsheet renders the one-page quick reference (docs/cheatsheet.md).
func Cheatsheet(root *cobra.Command) string {
	cmds := visibleCommands(root)
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — cheat sheet\n\n%s\n\n", branding.B.Title, generatedNote)

	b.WriteString("## Commands\n\n| Command | What it does |\n|---|---|\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| `%s %s` | %s |\n", branding.B.Name, useArgs(c), c.Short)
	}
	b.WriteString("\n")

	b.WriteString("## Key flags\n\n")
	for _, c := range cmds {
		flags := keyFlags(c)
		if len(flags) == 0 {
			continue
		}
		fmt.Fprintf(&b, "**`%s`** — %s\n\n", c.Name(), strings.Join(flags, ", "))
	}

	b.WriteString(workflows())
	return b.String()
}

// visibleCommands returns the user-facing subcommands, alphabetized, dropping
// cobra's built-in help/completion and any hidden commands.
func visibleCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range root.Commands() {
		if c.Hidden || c.IsAdditionalHelpTopicCommand() || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

func flagsTable(c *cobra.Command) string {
	var rows []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		rows = append(rows, fmt.Sprintf("| `--%s` | %s | %s |", f.Name, codeOrDash(f.DefValue), f.Usage))
	})
	if len(rows) == 0 {
		return ""
	}
	return "| Flag | Default | Description |\n|---|---|---|\n" + strings.Join(rows, "\n") + "\n"
}

func keyFlags(c *cobra.Command) []string {
	var out []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		out = append(out, "`--"+f.Name+"`")
	})
	return out
}

// useArgs is the positional-args portion of the use line, e.g. "start <name>".
func useArgs(c *cobra.Command) string {
	return strings.TrimSpace(strings.TrimSuffix(c.Use, "[flags]"))
}

// useArgsWithFlags is the args portion plus cobra's "[flags]" placeholder.
func useArgsWithFlags(c *cobra.Command) string {
	u := useArgs(c)
	if c.HasAvailableLocalFlags() {
		u += " [flags]"
	}
	return u
}

func codeOrDash(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + s + "`"
}

func workflows() string {
	n := branding.B.Name
	b := branding.B
	return fmt.Sprintf(`
## Common workflows

**Start a stack**
`+"```"+`sh
git checkout %[8]s
%[1]s %[2]s feature-a     # branch off the trunk
# ...commit work...
%[1]s %[2]s feature-b     # branch off feature-a (current branch)
# ...commit work...
`+"```"+`

**Open / refresh PRs**
`+"```"+`sh
export %[9]s=$(gh auth token)
%[1]s %[4]s --owner ORG --repo REPO
`+"```"+`

**Restack after the parent changes**
`+"```"+`sh
# amend or add commits to feature-a, then:
%[1]s %[3]s                # cascade-rebase children onto the new tips
%[1]s %[4]s --owner ORG --repo REPO
`+"```"+`

**Adopt a teammate's stack**
`+"```"+`sh
%[1]s %[5]s 123 --owner ORG --repo REPO   # reconstruct from PR #123
%[1]s %[3]s
`+"```"+`

**Move a branch to a new parent**
`+"```"+`sh
%[1]s %[6]s feature-b --onto feature-c
%[1]s %[3]s
`+"```"+`

**Drop a branch from the stack**
`+"```"+`sh
%[1]s %[7]s feature-b --close-pr --delete-branch --owner ORG --repo REPO
`+"```"+`
`, n, b.CmdStart, b.CmdSync, b.CmdSubmit, b.CmdAdopt, b.CmdReparent, b.CmdRemove, "main", b.Env("TOKEN"))
}
